import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/homePage/header/header";
import TopBar from "./_components/homePage/topBar/topBar";
import Footer from "./_components/homePage/footer/footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
          />
      </head>
      <body className={inter.className}>
        <TopBar />
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
